# Generated by Django 4.1.1 on 2023-04-20 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('department', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('salary_class', models.CharField(choices=[('l', 'low'), ('m', 'medium'), ('h', 'high')], default='l', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('in_dept', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=7)),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apip1.boss')),
            ],
        ),
        migrations.AddField(
            model_name='boss',
            name='favemp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apip1.employee'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apip1.author')),
            ],
        ),
    ]
