# Generated by Django 4.1.1 on 2022-11-18 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apip1', '0002_boss_employee_worker_boss_favemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='boss',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apip1.boss'),
        ),
    ]
